import Head from "next/head";
import type { ReactElement } from "react";
import MainLayout from "../components/layouts/mainLayout";
import type { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Whiz Kids Baseball</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#FFFFFF] to-[#C2C2C2]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[7rem]">
            <span className="font-extrabold text-[#CC0007]">Whiz Kids</span>
            <span className="text-[#1F1F1F] sm:text-[4rem]">Baseball</span>
          </h1>
        </div>
      </main>
      <main className="flex min-h-[75vh] flex-col items-center bg-[#1F1F1F]">
        <div className="container flex flex-col items-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[4rem]">
            <span className="font-extrabold text-[#FFFFFF]">About Us</span>
          </h1>
          <h5>
            <span className="font-light text-[#C2C2C2] sm:text-[2rem]">
              We aren&rsquo;t one of those organizations that makes claims like
              &apos;Only the best play here.&apos; We aren&rsquo;t going to
              posture for your business by promising exposure or leveraging
              relationships with head coaches. As far as exposure goes, our
              stance is pretty straight forward. If you aren&rsquo;t driven to
              be the best version of yourself in the game of baseball, you will
              eventually get exposed.
              <br />
              <br />
              Great players get recruited. Great players can play anywhere and
              get recruited. Great players need guidance to push themselves
              beyond the scope of their immediate competitive standing. There is
              a good chance that you aren&rsquo;t currently great. Perhaps you
              dream of greatness. That&rsquo;s awesome. We will do our best to
              educate you on where y ou currenlty stand and guide you through
              the process of reaching your potential. Stop worrying about your
              opportunities and your exposure. Get in the drivers seat.
              <br />
              <br />
              This is an environment where normal baseball players with big
              dreams show up to work consistently and ultimately transform
              themselves. We aim to mentor players who eventually get recruited.
              <br />
              <br />
              We are passionate, straight forward and very well informed. Our
              mission is to always be equipped to push you further.
            </span>
          </h5>
        </div>
      </main>

      <main className="min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#FFFFFF] to-[#C2C2C2]">
        <div className="flex flex-col items-center gap-2 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-[#1F1F1F] sm:text-[4rem]">
            Contact Us
          </h1>
          <h5>
            Interested in Whiz Kids and have any questions? Feel free to reach
            out to us!
          </h5>
        </div>

        <form action="#" method="POST">
          <div className="mx-[25vh] rounded-[40px] bg-[#1F1F1F] p-20">
            <h1 className="text-5xl font-extrabold tracking-tight text-[#FFFFFF] sm:text-[4rem]">
              Player Information
            </h1>

            <div className="row-auto m-10 grid grid-cols-6 gap-6">
              <div className="col-span-3">
                <label
                  htmlFor="first-name"
                  className="text-2xl text-[#FFFFFF] "
                >
                  First Name
                </label>
                <input
                  type="text"
                  name="first-name"
                  id="first-name"
                  autoComplete="first-name"
                  className="
                      text-md 
                      block
                      w-full
                      rounded-lg 
                      p-2.5 
                      text-gray-900
                    "
                />
              </div>

              <div className="col-span-3">
                <label htmlFor="last-name" className="text-2xl text-[#FFFFFF] ">
                  Last Name
                </label>
                <input
                  type="text"
                  name="last-name"
                  id="last-name"
                  autoComplete="last-name"
                  className="
                      text-md 
                      block
                      w-full
                      rounded-lg 
                      p-2.5 
                      text-gray-900
                    "
                />
              </div>

              <div className="col-span-4">
                <label htmlFor="email" className="text-2xl text-[#FFFFFF] ">
                  Email
                </label>
                <input
                  type="text"
                  name="email"
                  id="email"
                  autoComplete="email"
                  className="
                      text-md 
                      block
                      w-full
                      rounded-lg 
                      p-2.5 
                      text-gray-900
                    "
                />
              </div>

              <div className="col-span-2">
                <label htmlFor="position" className="text-2xl text-[#FFFFFF] ">
                  Position
                </label>
                <input
                  type="text"
                  name="position"
                  id="position"
                  autoComplete="position"
                  className="
                      text-md 
                      block
                      w-full
                      rounded-lg 
                      p-2.5 
                      text-gray-900
                    "
                />
              </div>

              <div className="col-span-6">
                <label htmlFor="position" className="text-2xl text-[#FFFFFF] ">
                  Message
                </label>
                <input
                  type="text"
                  name="position"
                  id="position"
                  autoComplete="position"
                  className="
                      text-md 
                      block
                      w-full
                      rounded-lg 
                      p-2.5 
                      text-gray-900
                    "
                />
              </div>

              <button
                type="submit"
                className="
                    w-full 
                    rounded-lg 
                    bg-[#CC0007]  
                    px-5 
                    py-2.5 
                    text-center 
                    text-sm 
                    font-medium 
                    text-white hover:bg-[#FF141A] 
                    focus:outline-none 
                    focus:ring-4 
                    focus:ring-blue-300 
                    sm:w-auto
                    "
              >
                Submit
              </button>
            </div>
          </div>
        </form>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => {
  return (
    <>
      <MainLayout>{page}</MainLayout>
    </>
  );
};

export default Home;
